# Generated by Django 5.0.6 on 2026-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_user_managers_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
